### ISSUE TITLE
Comments have the same color as Annotations

### ISSUE THREAD

**Issue by paetrik** [SAP-samples/vscode-abap-cds#3]
Would it be possible to have different color for comments?

![image](https://user-images.githubusercontent.com/13899394/57704630-962e4c80-7662-11e9-81dc-9a3538156de2.png)

**Comment by FreHu** [comment]
The plugin does not decide the colors. It only assigns some labels (scopes) to the content.
Editor themes provide colors for most standard scopes. Annotations are something not present in other languages, so I labeled them as comments so that they get some highlighting by default.

I did however add some more specifics to annotation scopes so that people can recolor them.

I don't believe I can bundle this with the plugin, I'd have to make a custom theme. But you can customize the colors in your settings.json

Example for annotations (leading @ symbol can be colored separately):
```json
"editor.tokenColorCustomizations": {
      "[Default Dark+]": {
        "textMateRules": [
          {
            "scope": "comment.line.annotation.symbol.abapcds",
            "settings": {
              "foreground": "#40c386"
            }
          },
          {
            "scope": "comment.line.annotation.property.abapcds",
            "settings": {
              "foreground": "#bbbda0"
            }
          }
        ]
      }
    }
```

The used scopes can be found in
https://github.com/FreHu/vscode-cds-highlighting/blob/master/syntaxes/cds.tmLanguage.json
or by using this command
![image](https://user-images.githubusercontent.com/5097067/57706154-7cdacf80-7665-11e9-9592-a451ee737e0a.png)
